# Generated by Django 6.0.2 on 2026-02-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PRICE", "Pending Price"),
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("PAYMENT_UPLOADED", "Payment Uploaded"),
                            ("PAID", "Paid"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_PRICE",
                        max_length=20,
                    ),
                ),
                (
                    "receipt",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CIRCLE", "Circle"),
                            ("SQUARE", "Square"),
                            ("MAP", "Map (DXF/DWG)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dimension",
                    models.FloatField(
                        blank=True,
                        help_text="Dimension in mm (Radius for Circle, Side for Square)",
                        null=True,
                    ),
                ),
                (
                    "map_file",
                    models.FileField(blank=True, null=True, upload_to="maps/"),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, help_text="Weight in kg", null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Price in Tomans",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
